# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/android:api-29-ndk
        environment:
          go_version=1.14
    steps:
      - run: sudo apt-get install gcc libgl1-mesa-dev
      - run: echo ${go_version}
      - run: curl -O https://storage.googleapis.com/golang/go${go_version}.linux-amd64.tar.gz
      - run: tar -C /usr/local -xzf go${go_version}.linux-amd64.tar.gz
      - run: export PATH=$PATH:/usr/local/go/bin
      - run: export PATH /usr/local/go/bin:$PATH
      - run: go get fyne.io/fyne
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go build
      - run: fyne package -os android -appID com.example.myapp -icon Icon.png
