# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/android:api-29-ndk
    steps:
      - run: sudo apt-get install gcc libgl1-mesa-dev
      - run: curl --silent --show-error --location --fail --retry 3 --output /tmp/go1.14.tgz \
          "https://golang.org/dl/go$1.14.linux-amd64.tar.gz" && \
          sudo tar -C /usr/local -xzf /tmp/go1.14.tgz; \
          rm /tmp/go1.14.tgz
      - run: export PATH /usr/local/go/bin:$PATH
      - run: go get fyne.io/fyne
      - checkout
      # specify any bash command here prefixed with `run: `
      - run: go build
      - run: fyne package -os android -appID com.example.myapp -icon Icon.png
